FILENAME_BASE = whipple-id-abstract-bmd-2013

pdf:
	pdflatex $(FILENAME_BASE).tex
	pdflatex $(FILENAME_BASE).tex

clean:
	(rm -rf *.ps *.log *.dvi *.aux *.*% *.lof *.lop *.lot *.toc *.idx *.ilg *.ind *.bbl *blg)
